### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by eschava** [tkurki/grafana-track-map#7]
Trying to setup map with InfluxDB data source

TypeError: Cannot read property 'length' of undefined
    at f.eval (http://localhost:3000/public/plugins/grafana-map-panel/clock_ctrl.js?bust=1499773064073:119:51)
    at f.emit (http://localhost:3000/public/app/boot.js:61:19125)
    at a.emit (http://localhost:3000/public/app/boot.js:61:21443)
    at ClockCtrl.b.handleQueryResult (http://localhost:3000/public/app/boot.js:55:20950)
    at i (http://localhost:3000/public/app/boot.js:51:24759)
    at http://localhost:3000/public/app/boot.js:51:25181
    at o.$eval (http://localhost:3000/public/app/boot.js:52:293)
    at o.$digest (http://localhost:3000/public/app/boot.js:51:30809)
    at o.$apply (http://localhost:3000/public/app/boot.js:52:576)
    at http://localhost:3000/public/app/boot.js:51:28669

**Comment by tkurki** [comment]
ef7fba5366cc66932babf2a38d47b0ea144f384f

I have abandoned this project, feel free to fork & assume ownership.
